
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VendingMachines.Models
{

using System;
    using System.Collections.ObjectModel;
    
public partial class TerminalsProduct
{

    public string ProductId { get; set; }

    public int TerminalId { get; set; }

    public int Quantity { get; set; }



    public virtual Product Product { get; set; }

    public virtual Terminal Terminal { get; set; }

}

}
