
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VendingMachines.Models
{

using System;
    using System.Collections.ObjectModel;
    
public partial class TerminalsBill
{

    public int BillId { get; set; }

    public int TerminalId { get; set; }

    public int InsertedQuantity { get; set; }



    public virtual Bill Bill { get; set; }

    public virtual Terminal Terminal { get; set; }

}

}
