
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VendingMachines.Models
{

using System;
    using System.Collections.ObjectModel;
    
public partial class TerminalsCoin
{

    public int CoinId { get; set; }

    public int TerminalId { get; set; }

    public int ReturnedQuantity { get; set; }

    public int LoadedQuantity { get; set; }



    public virtual Coin Coin { get; set; }

    public virtual Terminal Terminal { get; set; }

}

}
