
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VendingMachines.Models
{

using System;
    using System.Collections.ObjectModel;
    
public partial class Terminal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Terminal()
    {

        this.TerminalsBills = new ObservableCollection<TerminalsBill>();

        this.TerminalsCoins = new ObservableCollection<TerminalsCoin>();

        this.TerminalsProducts = new ObservableCollection<TerminalsProduct>();

        this.SoldProducts = new ObservableCollection<SoldProduct>();

    }


    public int Id { get; set; }

    public string Location { get; set; }

    public int BillsCapacity { get; set; }

    public int CoinsLoadedQty { get; set; }

    public int ProductsLoadedQty { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<TerminalsBill> TerminalsBills { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<TerminalsCoin> TerminalsCoins { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<TerminalsProduct> TerminalsProducts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<SoldProduct> SoldProducts { get; set; }

}

}
